# Starting from a minimalist image
FROM ruby:2.6.5
# Reference for help contact me
LABEL maintainer="chris@adadev.org"

RUN apt-get update && apt-get install -y \
  curl \
  build-essential \
  postgresql \
  libpq-dev &&\
  curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && apt-get install -y nodejs yarn

RUN service postgresql start
RUN psql -c "CREATE ROLE tasklist WITH LOGIN PASSWORD 'tasklist' " postgres


# Create a directory for the app
RUN mkdir /app

# Set the working directory for RUN, ADD and COPY
WORKDIR /app

# Add entire student fork (overwrites previously added files)
#ARG SUBMISSION_SUBFOLDER
#ADD $SUBMISSION_SUBFOLDER /app

COPY Gemfile .
COPY Gemfile.lock .
RUN gem install bundler
RUN bundle install

COPY . .

# If needed copy original Gemfile
# COPY ./Gemfile .
RUN yarn install

# Overwrite the script and test files
ADD test.sh /app
ADD test /app

RUN chmod +x test.sh

CMD ["/app/test.sh"]

